### ISSUE TITLE
Enhancement: Should add output flag to the submission script

### ISSUE THREAD

**Issue by Nithishwer** [bigginlab/ABFE_workflow#18]
When I ran example execution.sh with bash, I got an error saying that:

Traceback (most recent call last):
  File "/biggin/b211/reub0138/mambaforge/envs/abfe/bin/cli-abfe", line 16, in <module>
    sys.exit(main())
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe_cli/ABFECalculator.py", line 56, in main
    res = calculate_abfe(protein_pdb_path=args.protein_pdb_path, ligand_sdf_paths=sdf_paths, out_root_folder_path=args.output_dir_path,
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe/calculate_abfe.py", line 32, in calculate_abfe
    os.mkdir(dir_path).

FileNotFoundError: [Errno 2] No such file or directory: '/scratch/riesbenj/ABFE/CyclophilinD_selfParametrized'

This is because the output directory was unspecified. Therefore, I had to add the following to the cli-abfe call in the submission script:

      -o /biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/examples/out

This seemed to fix the issue

**Comment by RiesBen** [comment]
good catch! Fixed.
