### ISSUE TITLE
Trying to access undeclared variable: input_sdf_

### ISSUE THREAD

**Issue by Nithishwer** [bigginlab/ABFE_workflow#19]
Executing bash example_execution_gmx.sh ends up with:

Traceback (most recent call last):
  File "/biggin/b211/reub0138/mambaforge/envs/abfe/bin/cli-abfe-gmx", line 12, in <module>
    sys.exit(main())
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe_cli/ABFECalculatorGmx.py", line 50, in main
    res = calculate_abfe_gmx(input_dir=args.gmx_files_root_dir, out_root_folder_path=args.output_dir_path, approach_name=args.project_name,
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe/calculate_abfe_gmx.py", line 70, in calculate_abfe_gmx
    job_approach_file_path = build_approach_flow(approach_name=approach_name,
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe/orchestration/build_approach_flow.py", line 23, in build_approach_flow
    generate_conf.generate_approach_conf(out_path=approach_conf_path,
TypeError: generate_approach_conf() missing 1 required positional argument: 'small_mol_ff'

build_approach_flow.py fails to provide small_mol_ff as argument to generate_conf.generate_approach_conf() 

Not sure how to deal with this.

**Comment by RiesBen** [comment]
hm... I see,
I think I fixed this with: https://github.com/bigginlab/ABFE_workflow/commit/b3df0c5f1774bf416c477574c12a8f23839f8bc6

Can you try the script again?

**Comment by Nithishwer** [comment]
I think this might be taken care of. But I am getting another error raised in #21 

Thanks
