### ISSUE TITLE
Nonetype error with cluster config

### ISSUE THREAD

**Issue by Nithishwer** [bigginlab/ABFE_workflow#22]
Running example_execution.sh with the nosubmit flag on bash gives: 

Prepare
```
	starting preparing ABFE-ligand file structur
		Ligand:  ligand-4
Traceback (most recent call last):
  File "/biggin/b211/reub0138/mambaforge/envs/abfe2/bin/cli-abfe", line 9, in <module>
    sys.exit(main())
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe_cli/ABFECalculator.py", line 55, in main
    res = calculate_abfe(protein_pdb_path=args.protein_pdb_path, ligand_sdf_paths=sdf_paths, out_root_folder_path=args.output_dir_path,
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe/calculate_abfe.py", line 45, in calculate_abfe
    build_ligand_flows(input_ligand_paths=conf["input_ligands_sdf_path"],
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe/orchestration/build_ligand_flow.py", line 215, in build_ligand_flows
    build_replicas_simulation_flow(out_ligand_path=out_ligand_path,
  File "/biggin/b211/reub0138/Projects/abfe/IrfansPaper/ABFE_workflow-main/abfe/orchestration/build_ligand_flow.py", line 78, in build_replicas_simulation_flow
    cluster_config['partition'] = "cpu"
TypeError: 'NoneType' object does not support item assignment
```

**Comment by RiesBen** [comment]
this one should be fixed now: [53ed34f](https://github.com/bigginlab/ABFE_workflow/commit/53ed34f06c6cd79ceaa0dae67560ee57dae1ad30)
