### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by lake-chao** [bigginlab/ABFE_workflow#30]
I installed abfe_workflow, and picked one pdbbind entry, 3pe1, for test. When I ran using cli

cli-abfe -p 3pe1.pdb -l 3pe1_ligands -nr 3 -njr 8 -njl 8 -nosubmit -nogpu -nohybrid -o output
 
Unfortunately, I got following errors:
 
Prepare
      starting preparing ABFE-ligand file structur
            Ligand:  ligand-1
Traceback (most recent call last):
  File "/opt/conda/envs/abfe/bin/cli-abfe", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/abfe/lib/python3.10/site-packages/abfe_cli/ABFECalculator.py", line 54, in main
    res = calculate_abfe(protein_pdb_path=args.protein_pdb_path, ligand_sdf_paths=sdf_paths, out_root_folder_path=args.output_dir_path,
  File "/opt/conda/envs/abfe/lib/python3.10/site-packages/abfe/calculate_abfe.py", line 45, in calculate_abfe
    build_ligand_flows(input_ligand_paths=conf["input_ligands_sdf_path"],
  File "/opt/conda/envs/abfe/lib/python3.10/site-packages/abfe/orchestration/build_ligand_flow.py", line 213, in build_ligand_flows
    build_replicas_simulation_flow(out_ligand_path=out_ligand_path,
  File "/opt/conda/envs/abfe/lib/python3.10/site-packages/abfe/orchestration/build_ligand_flow.py", line 179, in build_replicas_simulation_flow
    _ = scheduler.generate_scheduler_file(out_prefix=f"{approach_name}_{ligand_rep_name}")
  File "/opt/conda/envs/abfe/lib/python3.10/site-packages/abfe/orchestration/generate_scheduler.py", line 38, in generate_scheduler_file
    cluster_config = copy.deepcopy(self.cluster_config["Snakemake_job"])

TypeError: 'NoneType' object is not subscriptable

Thank you.

**Comment by philbiggin** [comment]
@RiesBen - are you able to pick up?

**Comment by RiesBen** [comment]
Hi @lake-chao,
first time ever I see this, I have a bit of a packed week, but I try to look into this, this week.

**Comment by lake-chao** [comment]
Thank you so much.

No hurry on this. I am just trying to get it work and see how it performs
on pdbbind entries.

**Comment by RobertArbon** [comment]
Hi folks, 

I've come across the same problem.  When running with `-nosubmit`  the the cluster configuration is `None` which, as @lake-chao  points out means the `Scheduler.generate_scheduler_file` method can't run. Instead of their suggestion, i've changed how the nosbumit flag gets parsed in the cli, see https://github.com/bigginlab/ABFE_workflow/pull/34
